filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log

  - type: mqtt
    hosts: ["tcp://mosquitto:1883"]
    topics:
      - "#"
    client_id: filebeat_mqtt

output.kafka:
  hosts: ["kafka:9092"]
  topic: "log"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

output.file:
  path: "/var/log/mqtt"
  filename: mqtt.log
