filebeat.inputs:
  # - type: log
  #   enabled: true
  #   paths:
  #     - /var/log/*.log

  # mqtt로 받을 때
  # - type: mqtt
  #   hosts: ["tcp://mosquitto:1883"]
  #   topics:
  #     - "#"
  #   client_id: filebeat_mqtt

  # REST 통신 - 온도
  - type: http_endpoint
    enabled: true
    listen_address: 0.0.0.0
    listen_port: 8082
    response_code: 200
    response_body: '{"message": "success"}'
    url: "/api/v1/temperature"
    prefix: "json"

  # # REST 통신 - 전도
  # - type: http_endpoint
  #   enabled: true
  #   listen_address: 0.0.0.0
  #   listen_port: 8083
  #   response_code: 200
  #   response_body: '{"message": "success"}'
  #   url: "/api/v1/conductivity"
  #   prefix: "json"
  
  # # REST 통신 - DO
  # - type: http_endpoint
  #   enabled: true
  #   listen_address: 0.0.0.0
  #   listen_port: 8084
  #   response_code: 200
  #   response_body: '{"message": "success"}'
  #   url: "/api/v1/do"
  #   prefix: "json"
  
  # # REST 통신 - pH
  # - type: http_endpoint
  #   enabled: true
  #   listen_address: 0.0.0.0
  #   listen_port: 8085
  #   response_code: 200
  #   response_body: '{"message": "success"}'
  #   url: "/api/v1/ph"
  #   prefix: "json"

output.kafka:
  hosts: 
    - "kafka-kraft1:9092"
    - "kafka-kraft2:9093"
    - "kafka-kraft3:9094"
  topic: "log"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
