es_host: elasticsearch
es_port: 9200
use_ssl: False
verify_certs: True
es_username: "elastic"  # 필요한 경우 설정
es_password: "capstone3"  # 필요한 경우 설정

writeback_index: elastalert_status
buffer_time:
  minutes: 15
run_every:
  minutes: 1
alert_time_limit:
  days: 2

rules_folder: /opt/elastalert/rules  # 규칙 파일 경로 설정